### ISSUE TITLE
Works with T800

### ISSUE THREAD

**Issue by surfingbytes** [iprak/winix#86]
Not an issue, just want to confirm this integration works with Winix T800, so maybe worth adding it to supported models.

**Comment by iprak** [comment]
Thanks, added to Readme.

**Comment by surfingbytes** [comment]
Yes, I use it in automations, and for similar reasons I never use auto mode. You can set the fan speed via Fan actions:

```
          - action: fan.set_preset_mode
            metadata: {}
            data:
              preset_mode: Manual (PlasmaWave off)
            target:
              entity_id: fan.bedroom_air_purifier
          - action: fan.set_percentage
            metadata: {}
            data:
              percentage: 75
            target:
              entity_id: fan.bedroom_air_purifier
```
